export enum AdminPermissionCode {
  FEATURE_FLAGS_WRITE = "FEATURE_FLAGS_WRITE",
  FEATURE_FLAGS_READ = "FEATURE_FLAGS_READ",
  AUDIT_READ = "AUDIT_READ",
  COUNTRY_MANAGE = "COUNTRY_MANAGE",
  USERS_MANAGE = "USERS_MANAGE",
}